package base.constants;

/**
 * @author kikyou
 * Created at 2020/2/2
 * UNIT:byte
 */
public interface Packets {

    int FILED_ID_LENGTH = 4;
    int FILED_HASH_LENGTH = 32;
    int FILED_CODE_LENGTH = 1;
    int FILED_LENGTH_LEN = 4;
    int FILED_IPV_LENGTH = 1;
    int FILED_IPV4_LENGTH = 4;
    int FILED_IPV6_LENGTH = 16;
    int FILED_CLOCK_LENGTH = 8;
    int FILED_IV_LENGTH = 16;
    int FILED_HOST_LENGTH = 2;

    int HEADERS_AUTH_REQ_LEN  = FILED_CODE_LENGTH + FILED_HASH_LENGTH;
    int HEADERS_AUTH_RESP_LEN = FILED_CODE_LENGTH + FILED_ID_LENGTH + FILED_IV_LENGTH;
    int HEADERS_DATA_REQ_LEN  = FILED_CODE_LENGTH + FILED_ID_LENGTH + FILED_LENGTH_LEN;
    int HEADERS_DATA_RESP_LEN = FILED_CODE_LENGTH + FILED_LENGTH_LEN;
    int HEADERS_CONNECT_REQ_LEN = FILED_CODE_LENGTH + FILED_ID_LENGTH;
    byte IPV4 = 0;
    byte IPV6 = 1;

}
